### ISSUE TITLE
Stub not created when extending/implementing external class/interface

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/VerveineJ#61] opened 2023-01-16 10:21 UTC
```java
public class MyClass extends External {}
```
If `External` is not defined in the source, the generated model doesn't make a stub and says `MyClass` extends `Object`.

**Comment by NicolasAnquetil** [comment] 2023-01-16 18:35
confirmed on latest eclipse on my computer.
Debugging can now start

**Comment by NicolasAnquetil** [comment] 2023-01-17 12:41
So it is more complicated than expected (who would have guessed it?)

We studied the problem for super-class which we do not have in the class path (not only a stub, but also an **unresolved** stub)
This is handled in:
- `VisitorInheritanceRef >> ensureInheritances()`
- `JavaDictionary >> ensureFamixClass()`

Both places explicitly say that if we do not have a binding for the super-class, then it becomes `Object`.
We can change that, but it should not be in 2 places, so I propose to remove it from  `JavaDictionary >> ensureFamixClass`.

Only problem is that it is a profound change in the organisation of VVJ :-(

**Comment by NicolasAnquetil** [comment] 2023-01-17 14:33
Note: seems o be working fine in v2. Something happened when we separated Interfaces from Classes (ie. created FamixJavaInterface)

**Comment by badetitou** [comment] 2023-01-23 08:46
I also tried to investigate using the Java debugger
It looks like the `ITypeBinding` do not have the interfaces resolved by jdt.
![image](https://user-images.githubusercontent.com/6225039/213997765-528c6cce-35b1-46f1-90f2-c5b11aa9d2a8.png)

But we can find it in the sub "binding" parameter superInterface
![image](https://user-images.githubusercontent.com/6225039/213997873-ca6bce5b-d6b7-4404-8850-d331558d2ee4.png)

Maybe we should for a way to get this value

**Closed as completed** 2023-01-25 15:49 UTC
